on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.client_secret }}
    - name: Deploy Azure Resource Manager (ARM) Template
      env: 
        target-env: dev
      uses: Azure/arm-deploy@v1.0.9
      with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          subscriptionId: bf620182-0925-45a8-81cc-aae619e6209c
         
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: gitopslearn
          # Specify the path or URL to the Azure Resource Manager template.
          template: ARM-Templates\container-webapp-template.json
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Incremental
          # Specifies the name of the resource group deployment to create.
          parameters: webAppName=highfivedevops-${{env.target-env}}
          # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
          
    
