# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
env: 
  registryName: highfivedevopsreg.azurecr.io
  repositoryName:  wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag:  ${{github.run_number}}
on:
  workflow_dispatch:
  push:
    paths:
      - Application/**
    branches: [ "main" ]
  pull_request:
    paths:
      - Application/**  
    branches: [ "main" ]
jobs:
  build:
    defaults:
      run:
        working-directory: Application/src/RazorPagesTestSample
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login ${{secrets.ACR_LOGIN_SERVER}} -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - run: docker build -t ${{env.registryName}}/${{env.repositoryName}}:${{env.tag}} --build-arg build_version=${{env.tag}} ${{env.dockerFolderPath}}
    - run: docker push ${{env.registryName}}/${{env.repositoryName}}:${{env.tag}} 

